"""coa

Revision ID: 23db527300a2
Revises: afd3e79df8a3
Create Date: 2026-05-17 19:41:04.818430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '23db527300a2'
down_revision: Union[str, None] = 'afd3e79df8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coa',
    sa.Column('coa_code', sa.String(length=20), nullable=True),
    sa.Column('coa_name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=20), nullable=True),
    sa.Column('coa_status', sa.String(length=100), nullable=True),
    sa.Column('coa_level', sa.String(length=100), nullable=True),
    sa.Column('normal_balance', sa.String(length=20), nullable=True),
    sa.Column('is_posting', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("lower(parent_id) in ('asset','liability','equity','revenue','expense')", name='ck_parent_id'),
    sa.CheckConstraint("lower(normal_balance) in ('debit','credit')", name='ck_coa_normal_balance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'coa_code', name='uq_accounts_owner_code'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_coa_biz_id'), 'coa', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_cli_id'), 'coa', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_created_by'), 'coa', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_id'), 'coa', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_ten_id'), 'coa', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_usr_id'), 'coa', ['usr_id'], unique=False, schema='too_acc')
    op.create_foreign_key(None, 'journal_entry_lines', 'coa', ['account_id'], ['id'], source_schema='too_acc', referent_schema='too_acc', ondelete='RESTRICT')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_constraint(None, 'journal_entry_lines', schema='too_acc', type_='foreignkey')
    op.drop_index(op.f('ix_too_acc_coa_usr_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_ten_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_created_by'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_cli_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_biz_id'), table_name='coa', schema='too_acc')
    op.drop_table('coa', schema='too_acc')
    # ### end Alembic commands ###
