"""add rls policy for users

Revision ID: 3c394844852b
Revises: 70edc6d3b2d7
Create Date: 2026-05-11 13:06:29.967881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3c394844852b'
down_revision: Union[str, None] = '70edc6d3b2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions_raw', sa.Column('ten_id', sa.Uuid(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('biz_id', sa.Uuid(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('usr_id', sa.Uuid(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('cli_id', sa.Uuid(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('usr_type', sa.String(length=32), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('created_by', sa.Uuid(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('b_int', sa.Integer(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('b_str', sa.String(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('b_date', sa.DateTime(timezone=True), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('b_bool', sa.Boolean(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('is_deleted', sa.Boolean(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('is_flag', sa.Boolean(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('locale', sa.String(length=32), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('type', sa.String(), nullable=True), schema='too_acc')
    op.add_column('transactions_raw', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='too_acc')
    op.drop_index(op.f('idx_transactions_owner_status'), table_name='transactions_raw', schema='too_acc')
    op.drop_constraint(op.f('uq_transactions_owner_hash'), 'transactions_raw', schema='too_acc', type_='unique')
    op.create_unique_constraint('uq_transactions_owner_hash', 'transactions_raw', ['ten_id', 'hash'], schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_biz_id'), 'transactions_raw', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_cli_id'), 'transactions_raw', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_created_by'), 'transactions_raw', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_id'), 'transactions_raw', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_ten_id'), 'transactions_raw', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_usr_id'), 'transactions_raw', ['usr_id'], unique=False, schema='too_acc')
    op.drop_column('transactions_raw', 'owner_id', schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.add_column('transactions_raw', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False), schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_usr_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_ten_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_created_by'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_cli_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_biz_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_constraint('uq_transactions_owner_hash', 'transactions_raw', schema='too_acc', type_='unique')
    op.create_unique_constraint(op.f('uq_transactions_owner_hash'), 'transactions_raw', ['owner_id', 'hash'], schema='too_acc', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_transactions_owner_status'), 'transactions_raw', ['owner_id', 'status', 'txn_date'], unique=False, schema='too_acc')
    op.drop_column('transactions_raw', 'extra', schema='too_acc')
    op.drop_column('transactions_raw', 'type', schema='too_acc')
    op.drop_column('transactions_raw', 'locale', schema='too_acc')
    op.drop_column('transactions_raw', 'is_flag', schema='too_acc')
    op.drop_column('transactions_raw', 'is_deleted', schema='too_acc')
    op.drop_column('transactions_raw', 'b_json', schema='too_acc')
    op.drop_column('transactions_raw', 'b_bool', schema='too_acc')
    op.drop_column('transactions_raw', 'b_date', schema='too_acc')
    op.drop_column('transactions_raw', 'b_decimal', schema='too_acc')
    op.drop_column('transactions_raw', 'b_str', schema='too_acc')
    op.drop_column('transactions_raw', 'b_int', schema='too_acc')
    op.drop_column('transactions_raw', 'created_by', schema='too_acc')
    op.drop_column('transactions_raw', 'usr_type', schema='too_acc')
    op.drop_column('transactions_raw', 'cli_id', schema='too_acc')
    op.drop_column('transactions_raw', 'usr_id', schema='too_acc')
    op.drop_column('transactions_raw', 'biz_id', schema='too_acc')
    op.drop_column('transactions_raw', 'ten_id', schema='too_acc')
    # ### end Alembic commands ###
