"""ztest

Revision ID: 70edc6d3b2d7
Revises: 81d8aa46b823
Create Date: 2026-05-10 17:14:58.530835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '70edc6d3b2d7'
down_revision: Union[str, None] = '81d8aa46b823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ztest',
    sa.Column('test1', sa.String(), nullable=True),
    sa.Column('test2', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_global'
    )
    op.create_index(op.f('ix_too_global_ztest_biz_id'), 'ztest', ['biz_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_ztest_cli_id'), 'ztest', ['cli_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_ztest_created_by'), 'ztest', ['created_by'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_ztest_id'), 'ztest', ['id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_ztest_ten_id'), 'ztest', ['ten_id'], unique=False, schema='too_global')
    op.create_index(op.f('ix_too_global_ztest_usr_id'), 'ztest', ['usr_id'], unique=False, schema='too_global')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_too_global_ztest_usr_id'), table_name='ztest', schema='too_global')
    op.drop_index(op.f('ix_too_global_ztest_ten_id'), table_name='ztest', schema='too_global')
    op.drop_index(op.f('ix_too_global_ztest_id'), table_name='ztest', schema='too_global')
    op.drop_index(op.f('ix_too_global_ztest_created_by'), table_name='ztest', schema='too_global')
    op.drop_index(op.f('ix_too_global_ztest_cli_id'), table_name='ztest', schema='too_global')
    op.drop_index(op.f('ix_too_global_ztest_biz_id'), table_name='ztest', schema='too_global')
    op.drop_table('ztest', schema='too_global')
    # ### end Alembic commands ###
