"""add rls policy for users

Revision ID: 963e96b078ee
Revises: 3c394844852b
Create Date: 2026-05-11 13:09:05.439060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '963e96b078ee'
down_revision: Union[str, None] = '3c394844852b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions_raw',
    sa.Column('source', sa.String(length=20), server_default=sa.text("'csv'"), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'CAD'"), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status in ('new','mapped','needs_review','posted')", name='ck_transactions_raw_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'hash', name='uq_transactions_owner_hash'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_transactions_raw_biz_id'), 'transactions_raw', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_cli_id'), 'transactions_raw', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_created_by'), 'transactions_raw', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_id'), 'transactions_raw', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_ten_id'), 'transactions_raw', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_usr_id'), 'transactions_raw', ['usr_id'], unique=False, schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_too_acc_transactions_raw_usr_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_ten_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_created_by'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_cli_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_biz_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_table('transactions_raw', schema='too_acc')
    # ### end Alembic commands ###
