"""add rls policy for users

Revision ID: 9d0ded7e6292
Revises: 963e96b078ee
Create Date: 2026-05-11 13:11:40.576522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9d0ded7e6292'
down_revision: Union[str, None] = '963e96b078ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='too_acc')
    op.alter_column('audit_events', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='too_acc')
    op.alter_column('audit_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='too_acc')
    op.alter_column('coa', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='too_acc')
    op.alter_column('coa', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='too_acc')
    op.alter_column('coa', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='too_acc')
    op.alter_column('journal_entries', 'entry_date',
               existing_type=sa.DATE(),
               nullable=True,
               schema='too_acc')
    op.alter_column('journal_entries', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"),
               schema='too_acc')
    op.alter_column('journal_entries', 'posted_by',
               existing_type=sa.UUID(),
               nullable=True,
               schema='too_acc')
    op.alter_column('journal_entries', 'posted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='too_acc')
    op.alter_column('journal_entries', 'period_yyyymm',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='too_acc')
    op.alter_column('journal_entries', 'is_reversal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'journal_entry_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'account_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'line_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               schema='too_acc')
    op.alter_column('period_closes', 'period_yyyymm',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='too_acc')
    op.alter_column('period_closes', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='too_acc')
    op.alter_column('transactions_raw', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'csv'::character varying"),
               schema='too_acc')
    op.alter_column('transactions_raw', 'txn_date',
               existing_type=sa.DATE(),
               nullable=True,
               schema='too_acc')
    op.alter_column('transactions_raw', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='too_acc')
    op.alter_column('transactions_raw', 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               schema='too_acc')
    op.alter_column('transactions_raw', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'CAD'::character varying"),
               schema='too_acc')
    op.alter_column('transactions_raw', 'hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               schema='too_acc')
    op.alter_column('transactions_raw', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"),
               schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.alter_column('transactions_raw', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"),
               schema='too_acc')
    op.alter_column('transactions_raw', 'hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               schema='too_acc')
    op.alter_column('transactions_raw', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'CAD'::character varying"),
               schema='too_acc')
    op.alter_column('transactions_raw', 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               schema='too_acc')
    op.alter_column('transactions_raw', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='too_acc')
    op.alter_column('transactions_raw', 'txn_date',
               existing_type=sa.DATE(),
               nullable=False,
               schema='too_acc')
    op.alter_column('transactions_raw', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'csv'::character varying"),
               schema='too_acc')
    op.alter_column('period_closes', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='too_acc')
    op.alter_column('period_closes', 'period_yyyymm',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'line_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'account_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='too_acc')
    op.alter_column('journal_entry_lines', 'journal_entry_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='too_acc')
    op.alter_column('journal_entries', 'is_reversal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='too_acc')
    op.alter_column('journal_entries', 'period_yyyymm',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='too_acc')
    op.alter_column('journal_entries', 'posted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='too_acc')
    op.alter_column('journal_entries', 'posted_by',
               existing_type=sa.UUID(),
               nullable=False,
               schema='too_acc')
    op.alter_column('journal_entries', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"),
               schema='too_acc')
    op.alter_column('journal_entries', 'entry_date',
               existing_type=sa.DATE(),
               nullable=False,
               schema='too_acc')
    op.alter_column('coa', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='too_acc')
    op.alter_column('coa', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='too_acc')
    op.alter_column('coa', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='too_acc')
    op.alter_column('audit_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='too_acc')
    op.alter_column('audit_events', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='too_acc')
    op.alter_column('audit_events', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='too_acc')
    # ### end Alembic commands ###
