"""add status

Revision ID: ae280b844d90
Revises: 9d0ded7e6292
Create Date: 2026-05-15 18:24:00.787038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ae280b844d90'
down_revision: Union[str, None] = '9d0ded7e6292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_acc_transactions_raw_biz_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_cli_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_created_by'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_ten_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_usr_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_table('transactions_raw', schema='too_acc')
    op.add_column('journal_entries', sa.Column('entry_status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=True), schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_column('journal_entries', 'entry_status', schema='too_acc')
    op.create_table('transactions_raw',
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'csv'::character varying"), autoincrement=False, nullable=True),
    sa.Column('source_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('txn_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'CAD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ten_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('biz_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cli_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usr_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('b_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_decimal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('b_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('b_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['new'::character varying, 'mapped'::character varying, 'needs_review'::character varying, 'posted'::character varying]::text[])", name=op.f('ck_transactions_raw_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_raw_pkey')),
    sa.UniqueConstraint('ten_id', 'hash', name=op.f('uq_transactions_owner_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_transactions_raw_usr_id'), 'transactions_raw', ['usr_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_ten_id'), 'transactions_raw', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_id'), 'transactions_raw', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_created_by'), 'transactions_raw', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_cli_id'), 'transactions_raw', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_biz_id'), 'transactions_raw', ['biz_id'], unique=False, schema='too_acc')
    # ### end Alembic commands ###
