"""coa

Revision ID: afd3e79df8a3
Revises: f69eef2e3ae0
Create Date: 2026-05-17 16:43:18.996555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'afd3e79df8a3'
down_revision: Union[str, None] = 'f69eef2e3ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coa', sa.Column('coa_code', sa.String(length=20), nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('coa_name', sa.String(length=255), nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('parent_id', sa.String(length=20), nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('coa_status', sa.String(length=100), nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('coa_level', sa.String(length=100), nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('normal_balance', sa.String(length=20), nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('is_posting', sa.Boolean(), nullable=True), schema='too_acc')
    op.drop_constraint(op.f('uq_accounts_owner_code'), 'coa', schema='too_acc', type_='unique')
    op.create_unique_constraint('uq_accounts_owner_code', 'coa', ['ten_id', 'coa_code'], schema='too_acc')
    op.drop_column('coa', 'subtype', schema='too_acc')
    op.drop_column('coa', 'name', schema='too_acc')
    op.drop_column('coa', 'code', schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.add_column('coa', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='too_acc')
    op.add_column('coa', sa.Column('subtype', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='too_acc')
    op.drop_constraint('uq_accounts_owner_code', 'coa', schema='too_acc', type_='unique')
    op.create_unique_constraint(op.f('uq_accounts_owner_code'), 'coa', ['ten_id', 'code'], schema='too_acc', postgresql_nulls_not_distinct=False)
    op.drop_column('coa', 'is_posting', schema='too_acc')
    op.drop_column('coa', 'normal_balance', schema='too_acc')
    op.drop_column('coa', 'coa_level', schema='too_acc')
    op.drop_column('coa', 'coa_status', schema='too_acc')
    op.drop_column('coa', 'parent_id', schema='too_acc')
    op.drop_column('coa', 'coa_name', schema='too_acc')
    op.drop_column('coa', 'coa_code', schema='too_acc')
    # ### end Alembic commands ###
