"""init_global

Revision ID: b06aa2ff73e5
Revises: da8163f41df9
Create Date: 2026-05-10 15:52:29.977518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'b06aa2ff73e5'
down_revision: Union[str, None] = 'da8163f41df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass;

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zbe', 'be_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='too_global')
    op.alter_column('zbe', 'be_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='too_global')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_user_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_ten_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_route'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_model'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_biz_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_user_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_ten_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_session_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_route'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_model'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_message_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_feedback_type'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_biz_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_constraint('uq_agent_cache_ten_key', 'ai_cache', schema='too_ai', type_='unique')
    op.drop_index(op.f('ix_too_ai_ai_cache_usr_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_ten_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_expires_at'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_created_by'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_cli_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_cache_key'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_biz_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_rag_eval_result_run_id'), table_name='rag_eval_result', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_rag_eval_result_dataset_id'), table_name='rag_eval_result', schema='too_ai')
    op.drop_table('rag_eval_result', schema='too_ai')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_usr_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_ten_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_created_by'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_cli_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_biz_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_table('journal_entry_lines', schema='too_acc')
    op.drop_table('rag_eval_run', schema='too_ai')
    op.drop_table('rag_eval_dataset', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_usr_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_ten_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_source_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_created_by'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_cli_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_biz_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index('ix_emb384_hnsw', table_name='payroll_history_384', schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.drop_table('payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_usr_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_ten_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_source_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_created_by'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_cli_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_biz_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index('ix_emb1024_hnsw', table_name='inv_1024', schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb1024': 'vector_cosine_ops'})
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.drop_table('inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_acc_transactions_raw_usr_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_ten_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_created_by'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_cli_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_biz_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_table('transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_usr_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_ten_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_created_by'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_cli_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_biz_id'), table_name='period_closes', schema='too_acc')
    op.drop_table('period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_vendors_name'), table_name='mcp_vendors', schema='too_acc')
    op.drop_table('mcp_vendors', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_bank_transactions_posted_at'), table_name='mcp_bank_transactions', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_bank_transactions_account_name'), table_name='mcp_bank_transactions', schema='too_acc')
    op.drop_table('mcp_bank_transactions', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_usr_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_ten_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_created_by'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_cli_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_biz_id'), table_name='journal_entries', schema='too_acc')
    op.drop_table('journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_usr_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_ten_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_created_by'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_cli_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_biz_id'), table_name='coa', schema='too_acc')
    op.drop_table('coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_usr_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_ten_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_created_by'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_cli_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_biz_id'), table_name='audit_events', schema='too_acc')
    op.drop_table('audit_events', schema='too_acc')
    # ### end Alembic commands ###
