"""autogenuuid

Revision ID: bcac990a0171
Revises: cc453f8d43eb
Create Date: 2026-05-18 13:56:07.505744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bcac990a0171'
down_revision: Union[str, None] = 'cc453f8d43eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coa', 'coa_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='too_acc')
    op.alter_column('coa', 'coa_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='too_acc')
    op.alter_column('coa', 'coa_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='too_acc')
    op.alter_column('coa', 'coa_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='too_acc')
    op.alter_column('coa', 'normal_balance',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='too_acc')
    op.drop_index(op.f('ix_emb1024_chunk_tsv_gin'), table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.create_index(op.f('ix_emb1024_chunk_tsv_gin'), 'inv_1024', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.alter_column('coa', 'normal_balance',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='too_acc')
    op.alter_column('coa', 'coa_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='too_acc')
    op.alter_column('coa', 'coa_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='too_acc')
    op.alter_column('coa', 'coa_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='too_acc')
    op.alter_column('coa', 'coa_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='too_acc')
    # ### end Alembic commands ###
