"""init

Revision ID: da8163f41df9
Revises: 
Create Date: 2026-05-10 15:47:23.724497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'da8163f41df9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_audit_events_biz_id'), 'audit_events', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_cli_id'), 'audit_events', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_created_by'), 'audit_events', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_id'), 'audit_events', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_ten_id'), 'audit_events', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_audit_events_usr_id'), 'audit_events', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('coa',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("type in ('asset','liability','equity','revenue','expense')", name='ck_accounts_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'code', name='uq_accounts_owner_code'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_coa_biz_id'), 'coa', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_cli_id'), 'coa', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_created_by'), 'coa', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_id'), 'coa', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_ten_id'), 'coa', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_coa_usr_id'), 'coa', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('journal_entries',
    sa.Column('entry_no', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('source_ref_id', sa.Uuid(), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('period_yyyymm', sa.Integer(), nullable=False),
    sa.Column('is_reversal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reversed_entry_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("source in ('manual','ai','import','reversal')", name='ck_journal_entries_source'),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['too_acc.journal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'entry_no', name='uq_journal_entries_owner_entry_no'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_journal_entries_biz_id'), 'journal_entries', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_cli_id'), 'journal_entries', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_created_by'), 'journal_entries', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_id'), 'journal_entries', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_ten_id'), 'journal_entries', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entries_usr_id'), 'journal_entries', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('mcp_bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('posted_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_mcp_bank_transactions_account_name'), 'mcp_bank_transactions', ['account_name'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_mcp_bank_transactions_posted_at'), 'mcp_bank_transactions', ['posted_at'], unique=False, schema='too_acc')
    op.create_table('mcp_vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_mcp_vendors_name'), 'mcp_vendors', ['name'], unique=True, schema='too_acc')
    op.create_table('period_closes',
    sa.Column('period_yyyymm', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'period_yyyymm', name='uq_period_closes_owner_period'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_period_closes_biz_id'), 'period_closes', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_cli_id'), 'period_closes', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_created_by'), 'period_closes', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_id'), 'period_closes', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_ten_id'), 'period_closes', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_period_closes_usr_id'), 'period_closes', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('transactions_raw',
    sa.Column('source', sa.String(length=20), server_default=sa.text("'csv'"), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'CAD'"), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status in ('new','mapped','needs_review','posted')", name='ck_transactions_raw_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'hash', name='uq_transactions_owner_hash'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_transactions_raw_biz_id'), 'transactions_raw', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_cli_id'), 'transactions_raw', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_created_by'), 'transactions_raw', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_id'), 'transactions_raw', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_ten_id'), 'transactions_raw', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_transactions_raw_usr_id'), 'transactions_raw', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('inv_1024',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.Column('text_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('emb1024', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_index('ix_emb1024_chunk_tsv_gin', 'inv_1024', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb1024_hnsw', 'inv_1024', ['emb1024'], unique=False, schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb1024': 'vector_cosine_ops'})
    op.create_index(op.f('ix_too_ai_inv_1024_biz_id'), 'inv_1024', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_cli_id'), 'inv_1024', ['cli_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_created_by'), 'inv_1024', ['created_by'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_id'), 'inv_1024', ['id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_source_id'), 'inv_1024', ['source_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_ten_id'), 'inv_1024', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_inv_1024_usr_id'), 'inv_1024', ['usr_id'], unique=False, schema='too_ai')
    op.create_table('payroll_history_384',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.Column('text_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('emb384', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, schema='too_ai', postgresql_using='gin')
    op.create_index('ix_emb384_hnsw', 'payroll_history_384', ['emb384'], unique=False, schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.create_index(op.f('ix_too_ai_payroll_history_384_biz_id'), 'payroll_history_384', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_cli_id'), 'payroll_history_384', ['cli_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_created_by'), 'payroll_history_384', ['created_by'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_id'), 'payroll_history_384', ['id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_source_id'), 'payroll_history_384', ['source_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_ten_id'), 'payroll_history_384', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_payroll_history_384_usr_id'), 'payroll_history_384', ['usr_id'], unique=False, schema='too_ai')
    op.create_table('rag_eval_dataset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('relevant_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_table('rag_eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('embedding_version', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_table('journal_entry_lines',
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('line_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('usr_id', sa.Uuid(), nullable=True),
    sa.Column('cli_id', sa.Uuid(), nullable=True),
    sa.Column('usr_type', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("line_type in ('debit','credit')", name='ck_journal_entry_lines_line_type'),
    sa.CheckConstraint('amount > 0', name='ck_journal_entry_lines_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['too_acc.coa.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['too_acc.journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='too_acc'
    )
    op.create_index(op.f('ix_too_acc_journal_entry_lines_biz_id'), 'journal_entry_lines', ['biz_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_cli_id'), 'journal_entry_lines', ['cli_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_created_by'), 'journal_entry_lines', ['created_by'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_ten_id'), 'journal_entry_lines', ['ten_id'], unique=False, schema='too_acc')
    op.create_index(op.f('ix_too_acc_journal_entry_lines_usr_id'), 'journal_entry_lines', ['usr_id'], unique=False, schema='too_acc')
    op.create_table('rag_eval_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('recall_at_k', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision_at_k', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('is_faithful', sa.Boolean(), nullable=True),
    sa.Column('eval_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['too_ai.rag_eval_dataset.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['too_ai.rag_eval_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='too_ai'
    )
    op.create_index(op.f('ix_too_ai_rag_eval_result_dataset_id'), 'rag_eval_result', ['dataset_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_rag_eval_result_run_id'), 'rag_eval_result', ['run_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_biz_id'), 'ai_cache', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_cli_id'), 'ai_cache', ['cli_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_created_by'), 'ai_cache', ['created_by'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_expires_at'), 'ai_cache', ['expires_at'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_id'), 'ai_cache', ['id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_ten_id'), 'ai_cache', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_cache_usr_id'), 'ai_cache', ['usr_id'], unique=False, schema='too_ai')
    op.create_unique_constraint('uq_agent_cache_ten_key', 'ai_cache', ['ten_id', 'cache_key'], schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_biz_id'), 'ai_feedback_event', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_feedback_type'), 'ai_feedback_event', ['feedback_type'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_message_id'), 'ai_feedback_event', ['message_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_model'), 'ai_feedback_event', ['model'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_route'), 'ai_feedback_event', ['route'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_session_id'), 'ai_feedback_event', ['session_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_ten_id'), 'ai_feedback_event', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_feedback_event_user_id'), 'ai_feedback_event', ['user_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_biz_id'), 'ai_guardrail_event', ['biz_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_model'), 'ai_guardrail_event', ['model'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_route'), 'ai_guardrail_event', ['route'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_ten_id'), 'ai_guardrail_event', ['ten_id'], unique=False, schema='too_ai')
    op.create_index(op.f('ix_too_ai_ai_guardrail_event_user_id'), 'ai_guardrail_event', ['user_id'], unique=False, schema='too_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_user_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_ten_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_route'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_model'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_guardrail_event_biz_id'), table_name='ai_guardrail_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_user_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_ten_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_session_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_route'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_model'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_message_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_feedback_type'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_feedback_event_biz_id'), table_name='ai_feedback_event', schema='too_ai')
    op.drop_constraint('uq_agent_cache_ten_key', 'ai_cache', schema='too_ai', type_='unique')
    op.drop_index(op.f('ix_too_ai_ai_cache_usr_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_ten_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_expires_at'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_created_by'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_cli_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_cache_key'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_ai_cache_biz_id'), table_name='ai_cache', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_rag_eval_result_run_id'), table_name='rag_eval_result', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_rag_eval_result_dataset_id'), table_name='rag_eval_result', schema='too_ai')
    op.drop_table('rag_eval_result', schema='too_ai')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_usr_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_ten_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_created_by'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_cli_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entry_lines_biz_id'), table_name='journal_entry_lines', schema='too_acc')
    op.drop_table('journal_entry_lines', schema='too_acc')
    op.drop_table('rag_eval_run', schema='too_ai')
    op.drop_table('rag_eval_dataset', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_usr_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_ten_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_source_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_created_by'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_cli_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_payroll_history_384_biz_id'), table_name='payroll_history_384', schema='too_ai')
    op.drop_index('ix_emb384_hnsw', table_name='payroll_history_384', schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', schema='too_ai', postgresql_using='gin')
    op.drop_table('payroll_history_384', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_usr_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_ten_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_source_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_created_by'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_cli_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_ai_inv_1024_biz_id'), table_name='inv_1024', schema='too_ai')
    op.drop_index('ix_emb1024_hnsw', table_name='inv_1024', schema='too_ai', postgresql_using='hnsw', postgresql_ops={'emb1024': 'vector_cosine_ops'})
    op.drop_index('ix_emb1024_chunk_tsv_gin', table_name='inv_1024', schema='too_ai', postgresql_using='gin')
    op.drop_table('inv_1024', schema='too_ai')
    op.drop_index(op.f('ix_too_acc_transactions_raw_usr_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_ten_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_created_by'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_cli_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_transactions_raw_biz_id'), table_name='transactions_raw', schema='too_acc')
    op.drop_table('transactions_raw', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_usr_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_ten_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_created_by'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_cli_id'), table_name='period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_period_closes_biz_id'), table_name='period_closes', schema='too_acc')
    op.drop_table('period_closes', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_vendors_name'), table_name='mcp_vendors', schema='too_acc')
    op.drop_table('mcp_vendors', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_bank_transactions_posted_at'), table_name='mcp_bank_transactions', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_mcp_bank_transactions_account_name'), table_name='mcp_bank_transactions', schema='too_acc')
    op.drop_table('mcp_bank_transactions', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_usr_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_ten_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_created_by'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_cli_id'), table_name='journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_journal_entries_biz_id'), table_name='journal_entries', schema='too_acc')
    op.drop_table('journal_entries', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_usr_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_ten_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_created_by'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_cli_id'), table_name='coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_coa_biz_id'), table_name='coa', schema='too_acc')
    op.drop_table('coa', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_usr_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_ten_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_created_by'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_cli_id'), table_name='audit_events', schema='too_acc')
    op.drop_index(op.f('ix_too_acc_audit_events_biz_id'), table_name='audit_events', schema='too_acc')
    op.drop_table('audit_events', schema='too_acc')
    # ### end Alembic commands ###
